### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by balupton** [rnestler/attractorr#55]
so I can do `cargo install torrent-search`

**Comment by rnestler** [comment]
I'm currently leaning to name it on of
 * Arrtractor
 * Attractorr

**Comment by balupton** [comment]
Using `cargo install --git https://github.com/rnestler/attractorr` installs as `attractor` due to:

https://github.com/rnestler/attractorr/blob/8d8e6c322a561741a5d41f54f44a9e6b78a06069/Cargo.toml#L2

Should the repo be changed to `rnestler/attractor` or should that toml line be changed?
